### ISSUE TITLE
Check ethnicity error

### ISSUE THREAD

**Issue by lemieuxl** [lemieuxl/pyGenClean#11]
When using the `check_ethnicity` script, there is an error if the `--skip-ref-pops` options. The automatic report fails when it tries to read the file `ethnicity.outliers` (which doesn't exists). The automatic report also needs to change its content if the `--skip-ref-pops` option is used.

**Comment by lemieuxl** [comment]
```
Traceback (most recent call last):
  File ".../pyGenClean_virt/bin/run_pyGenClean", line 9, in <module>
    load_entry_point('pyGenClean==1.7.1', 'console_scripts', 'run_pyGenClean')()
  File ".../pyGenClean_virt/pyGenClean/run_data_clean_up.py", line 3174, in safe_main
    main()
  File ".../pyGenClean_virt/pyGenClean/run_data_clean_up.py", line 186, in main
    options,
  File ".../pyGenClean_virt/pyGenClean/run_data_clean_up.py", line 1923, in run_check_ethnicity
    with open(script_prefix + ".outliers", "r") as i_file:
IOError: [Errno 2] No such file or directory: 'data_clean_up.2015-10-09_08.00.25/3_check_ethnicity/ethnicity.outliers'
```
